### ISSUE TITLE
'SF_DATALESS' undeclared

### ISSUE THREAD

**Issue by casperes1996** [jivanpal/apfs-tools#1]
Compiler: GCC 9.2.0_2 (homebrew.)

When compiling apfs-inspect gcc throws the following error:

In file included from src/apfs/func/btree.h:16,
```
                 from src/apfs-inspect.c:10:
src/apfs/func/../string/j.h: In function 'get_j_inode_bsd_flags_string':
src/apfs/func/../string/j.h:191:9: error: 'SF_DATALESS' undeclared (first use in this function)
  191 |         SF_DATALESS,
      |         ^~~~~~~~~~~
src/apfs/func/../string/j.h:191:9: note: each undeclared identifier is reported only once for each function it appears in
make: *** [obj/apfs-inspect.o] Error 1

```

Don't really know what else to add here.

**Comment by jivanpal** [comment]
From the APFS spec (2019-02-07, pp. 67–68):

> ## `j_inode_val_t`
> [...]
> ### `bsd_flags`
> The inodeʼs BSD flags.
> `uint32_t bsd_flags;`
> For information about these flags, see the `chflags(2)` man page and the `<sys/stat.h>` header file.

On my system, the constant `SF_DATALESS` is defined in `<sys/stat.h>`, which is provided by Xcode Command Line Tools at `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stat.h`.

`find "$(xcode-select -p)" -name 'stat.h'` shows that the following header files are provided by my Xcode installation:

- `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stat.h`
- `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stat.h`
- `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/stat.h`
- `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stat.h`

If you are running macOS 10.14 (Mojave) or 10.15 (Catalina) and have Xcode Command Line Tools installed (via `xcode-select --install`), your setup ought to be the same.

In order to diagnose further, please add a comment with the output of the following commands:

- `type gcc`
- `gcc --version`
- `xcode-select -p`
- `find "$(xcode-select -p)" -name 'stat.h'`

**Comment by jivanpal** [comment]
I have now checked my copy of `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/stat.h`, and it appears that all the necessary constants are defined there except for `SF_DATALESS`, causing compilation failure on Mojave.

Please add the line `#define SF_DATALESS 0x40000000` to `src/string/j.h` and let me know if this resolves the issue.

**Comment by casperes1996** [comment]
Bingo. Issue resolved. 

Cheers

**Comment by jivanpal** [comment]
Fixed upstream. Also added `print_j_file_extent_key()`, which I accidentally left out of a recent commit.
